"""initial schema

Revision ID: a3fbd94354cf
Revises: 
Create Date: 2026-07-17 09:31:50.806602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3fbd94354cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cost_per_sqm', sa.Float(), nullable=False),
    sa.Column('thickness_mm', sa.Float(), nullable=False),
    sa.Column('density_g_cm3', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tea_density_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('density_g_cm3', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tea_density_g_cm3', sa.Float(), nullable=False),
    sa.Column('package_weight_g', sa.Float(), nullable=False),
    sa.Column('shipment_quantity', sa.Float(), nullable=False),
    sa.Column('shipment_type', sa.String(length=20), nullable=False),
    sa.Column('package_shape', sa.String(length=20), nullable=False),
    sa.Column('packaging_material', sa.String(length=20), nullable=False),
    sa.Column('target_market', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('length_mm', sa.Float(), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('height_mm', sa.Float(), nullable=False),
    sa.Column('product_volume_cm3', sa.Float(), nullable=False),
    sa.Column('package_volume_cm3', sa.Float(), nullable=False),
    sa.Column('fill_ratio', sa.Float(), nullable=False),
    sa.Column('surface_area_m2', sa.Float(), nullable=False),
    sa.Column('material_usage_g', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('scenario_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('total_units_required', sa.Integer(), nullable=False),
    sa.Column('packaging_cost_current', sa.Float(), nullable=False),
    sa.Column('packaging_cost_ai', sa.Float(), nullable=False),
    sa.Column('freight_cost_current', sa.Float(), nullable=False),
    sa.Column('freight_cost_ai', sa.Float(), nullable=False),
    sa.Column('total_cost_current', sa.Float(), nullable=False),
    sa.Column('total_cost_ai', sa.Float(), nullable=False),
    sa.Column('total_savings', sa.Float(), nullable=False),
    sa.Column('savings_pct', sa.Float(), nullable=False),
    sa.Column('container_utilization_current', sa.Float(), nullable=False),
    sa.Column('container_utilization_ai', sa.Float(), nullable=False),
    sa.Column('comparison_table', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('cartons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('package_type_id', sa.UUID(), nullable=False),
    sa.Column('length_mm', sa.Float(), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('height_mm', sa.Float(), nullable=False),
    sa.Column('units_per_carton', sa.Integer(), nullable=False),
    sa.Column('carton_weight_kg', sa.Float(), nullable=False),
    sa.Column('board_grade', sa.String(length=50), nullable=False),
    sa.Column('carton_material_cost', sa.Float(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('scenario_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_type_id'], ['package_types.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('carton_id', sa.UUID(), nullable=False),
    sa.Column('cartons_per_layer', sa.Integer(), nullable=False),
    sa.Column('layers', sa.Integer(), nullable=False),
    sa.Column('cartons_per_pallet', sa.Integer(), nullable=False),
    sa.Column('pallet_height_mm', sa.Float(), nullable=False),
    sa.Column('total_weight_kg', sa.Float(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('scenario_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carton_id'], ['cartons.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('pallet_id', sa.UUID(), nullable=False),
    sa.Column('container_type', sa.String(length=10), nullable=False),
    sa.Column('pallets_per_container', sa.Integer(), nullable=False),
    sa.Column('cartons_per_container', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=False),
    sa.Column('empty_space', sa.Float(), nullable=False),
    sa.Column('containers_required', sa.Integer(), nullable=False),
    sa.Column('freight_cost', sa.Float(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('scenario_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('containers')
    op.drop_table('pallets')
    op.drop_table('cartons')
    op.drop_table('results')
    op.drop_table('package_types')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tea_density_profiles')
    op.drop_table('packaging_materials')
    # ### end Alembic commands ###
